version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        image: react-app
        container_name: react-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - 8082:80
        restart: unless-stopped